name: pusher_websocket_flutter
description: A Flutter plugin to listen to events sent through pusher. Wraps the native Java and Swift libraries
version: 0.0.5
author: HomeX Mobile Team <mobile@homex.com>
homepage: https://github.com/HomeXLabs/pusher-websocket-flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  json_annotation: ^2.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.5.2
  json_serializable: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    androidPackage: com.pusherwebsocket.pusher
    pluginClass: PusherPlugin